api:
  host: 0.0.0.0
  port: 7036
  debug: true
  middlewares:
    - "basic-auth"
  auth:
    username: "admin"
    password: "password"
  whitelist_ip:
    - "172.20.0.2"
    - "192.168.65.1"
    - "127.0.0.1"
    - "::1"

swagger:
  title: "Gobot server API"
  host: "localhost:7036"
  version: "1.0.0"
  protocol: "http"

postgres:
  dsn: "postgres://randomuser:randompassword@postgres:5432/randomdb"
